apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: compute

resources:
  - ray-compute.yaml
  - ingress.yaml

helmCharts:
- name: kuberay-operator
  repo: https://ray-project.github.io/kuberay-helm/
  version: 1.5.0
  releaseName: kuberay-operator
  namespace: compute
  valuesFile: ray-operator.yaml
