apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ray-compute
  labels:
    app.kubernetes.io/name: ray-compute
spec:
  rayVersion: '2.9.0'
  
  # Head pod on ubuntu
  headGroupSpec:
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      spec:
        restartPolicy: Always
        nodeSelector:
          node-type: compute
          beta.kubernetes.io/arch: amd64
        containers:
        - name: ray-head
          image: rayproject/ray:2.9.0-py311-cpu
          ports:
          - containerPort: 8265
            name: dashboard
          - containerPort: 10001
            name: client
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"

  # Worker pods on library
  workerGroupSpecs:
  - replicas: 1
    minReplicas: 1
    maxReplicas: 4
    groupName: workers
    rayStartParams:
      num-gpus: "1"
    template:
      spec:
        restartPolicy: OnFailure
        runtimeClassName: nvidia
        nodeSelector:
          node-type: compute
          beta.kubernetes.io/arch: amd64
        containers:
        - name: ray-worker
          image: rayproject/ray:2.9.0-py311-cpu
          resources:
            limits:
              cpu: "6"
              memory: "10Gi"
              # nvidia.com/gpu: "1"