enabled: true
stateful: true
image:
  repository: registry
  tag: "2"
replicas: 1
ports:
  - name: http
    containerPort: 5000
    protocol: TCP
persistence:
  enabled: true
  size: 100Gi
  mountPath: /var/lib/registry
  storageClass: local-path
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ubuntu
ingress:
  enabled: true
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Registry
    gethomepage.dev/group: Apps
    gethomepage.dev/description: Docker registry API
  hosts:
    - registry.home
