enabled: true
image:
  repository: ghcr.io/gethomepage/homepage
  tag: latest
replicas: 1
serviceAccountName: homepage
ports:
  - name: http
    containerPort: 3000
    protocol: TCP
volumeMounts:
  - mountPath: /app/config/custom.js
    name: homepage-config
    subPath: custom.js
  - mountPath: /app/config/logs
    name: logs
volumes:
  - name: homepage-config
    configMap:
      name: homepage
  - name: logs
    emptyDir: {}
env:
  - name: HOMEPAGE_ALLOWED_HOSTS
    value: homepage.home
ingress:
  enabled: true
  hosts:
    - homepage.home
