{{- $app := .Values -}}
{{- if and $app.enabled (not $app.stateful) (not (($app.cron | default dict).enabled | default false)) }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
spec:
  replicas: {{ $app.replicas | default 1 }}
  {{- if $app.hostNetwork }}
  strategy:
    type: Recreate
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}
      {{- include "homelab.podAnnotations" (dict "app" $app) | nindent 6 }}
    spec:
      {{- include "homelab.podSpec" (dict "key" .Release.Name "app" $app) | nindent 6 }}
{{- end }}
