{{- $app := .Values -}}
{{- if and $app.enabled $app.persistence $app.persistence.enabled (not $app.stateful) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
  {{- with $app.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ $app.persistence.storageClass | default "local-path" }}
  resources:
    requests:
      storage: {{ $app.persistence.size }}
{{- end }}
