apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - secrets.yaml
  - namespaces.yaml

  - external/k1max.yaml
  - external/router.yaml

  - apps/homepage/
  - apps/noip/
  - apps/registry/