apiVersion: v1
kind: Namespace
metadata:
  name: external
  labels:
    type: external-devices
---
apiVersion: v1
kind: Namespace
metadata:
  name: infrastructure
  labels:
    type: infrastructure-services