apiVersion: v1
kind: Secret
metadata:
  name: noip-secret
  namespace: infrastructure
type: Opaque
stringData:
  NOIP_USERNAME: "${NOIP_USERNAME}"
  NOIP_PASSWORD: "${NOIP_PASSWORD}"
  NOIP_HOSTNAMES: "${NOIP_HOSTNAMES}"
---
apiVersion: v1
kind: Secret
metadata:
  name: p3d-app-secret
  namespace: default
type: Opaque
stringData:
  CLERK_SECRET_KEY: "${CLERK_SECRET_KEY}"