{{- range $key, $app := .Values.apps }}
{{- if and $app.enabled $app.configMap }}
{{- $ingressIP := "" }}
{{- if $app.configMap.corefile }}
{{- $traefikSvc := lookup "v1" "Service" "kube-system" "traefik" }}
{{- if $traefikSvc }}
{{- if $traefikSvc.status.loadBalancer.ingress }}
{{- $ingressIP = (index $traefikSvc.status.loadBalancer.ingress 0).ip }}
{{- end }}
{{- end }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $key }}
data:
{{- if $app.configMap.corefile }}
  Corefile: |
{{ $app.configMap.corefile | replace "{{TRAEFIK_IP}}" $ingressIP | indent 4 }}
{{- end }}
{{- end }}
{{- end }}
{{- range $key, $app := .Values.apps }}
{{- if and $app.enabled $app.scrapeConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $key }}-scrape-config
data:
  scrape.yml: |
{{ $app.scrapeConfig | toYaml | indent 4 }}
{{- end }}
{{- end }}
