{{- range $key, $svc := .Values.externalServices }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  namespace: {{ $svc.namespace | default "default" }}
spec:
  ports:
{{- range $svc.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
{{- end }}
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ $key }}
  namespace: {{ $svc.namespace | default "default" }}
  labels:
    kubernetes.io/service-name: {{ $key }}
addressType: IPv4
ports:
{{- range $svc.ports }}
  - port: {{ .port }}
    protocol: {{ .protocol | default "TCP" }}
{{- end }}
endpoints:
  - addresses:
      - {{ $svc.externalIP }}
{{- end }}
{{- end }}