{{- range $key, $secret := .Values.secrets }}
{{- if $secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
  namespace: {{ $secret.namespace | default "default" }}
type: Opaque
stringData:
{{- range $k, $v := $secret.data }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
{{- end }}