{{- range $key, $app := .Values.apps }}
{{- if and $app.enabled $app.ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
    app.kubernetes.io/name: {{ $key }}
spec:
{{- if $app.stateful }}
  clusterIP: None
{{- else if $app.service }}
  type: {{ $app.service.type | default "ClusterIP" }}
{{- else }}
  type: ClusterIP
{{- end }}
  ports:
{{- range $app.ports }}
    - port: {{ .servicePort | default .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name }}
{{- if and $app.service (eq $app.service.type "NodePort") .nodePort }}
      nodePort: {{ .nodePort }}
{{- else if and $app.service (eq $app.service.type "NodePort") $app.service.nodePort }}
      nodePort: {{ $app.service.nodePort }}
{{- end }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ $key }}
{{- end }}
{{- end }}