apiVersion: v2
name: homelab
description: A Helm chart for homelab services
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: cert-manager
    version: 1.16.2
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled
  - name: metrics-server
    version: 3.12.2
    repository: https://kubernetes-sigs.github.io/metrics-server/
    condition: metrics-server.enabled
  - name: victoria-metrics-k8s-stack
    version: 0.72.4
    repository: https://victoriametrics.github.io/helm-charts/
    condition: victoria-metrics-k8s-stack.enabled