apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: registry
spec:
  rules:
    - host: "registry.home"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ui
  namespace: infrastructure
  labels:
    app.kubernetes.io/name: registry-ui
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Container Registry
    gethomepage.dev/group: Infrastructure
    gethomepage.dev/icon: docker.png
    gethomepage.dev/name: Container Registry
spec:
  rules:
    - host: "dashboard.registry.home"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: registry-ui
                port:
                  number: 80