apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: infrastructure
  labels:
    app: registry
spec:
  type: ClusterIP
  ports:
  - port: 5000
    protocol: TCP
  selector:
    app: registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry-ui
  namespace: infrastructure
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: registry-ui