apiVersion: apps/v1
kind: Deployment
metadata:
  name: noip-duc
  namespace: infrastructure
  labels:
    app: noip-duc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: noip-duc
  template:
    metadata:
      labels:
        app: noip-duc
    spec:
      containers:
      - name: noip-duc
        image: ghcr.io/noipcom/noip-duc:latest
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: noip-secret